// Objective-C API for talking to vbh/taf-wallet/api Go package.
//   gobind -lang=objc vbh/taf-wallet/api
//
// File is generated by gobind. Do not edit.

#ifndef __Api_H__
#define __Api_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class ApiAddCoinTypeRequest;
@class ApiAddCoinTypeResponse;
@class ApiAddCoinTypesRequest;
@class ApiAddCoinTypesResponse;
@class ApiAecoSignRequest;
@class ApiAecoSignRequestFromMaster;
@class ApiAecoSignResponse;
@class ApiAecoSignResponseFromMaster;
@class ApiBackupMnemonicRequest;
@class ApiBackupMnemonicResponse;
@class ApiBigInt;
@class ApiBigInts;
@class ApiBinaries;
@class ApiBools;
@class ApiCreateMnemonicRequest;
@class ApiCreateMnemonicResponse;
@class ApiCreateWalletRequest;
@class ApiCreateWalletResponse;
@class ApiETHEipAddressRequest;
@class ApiETHEipAddressResponse;
@class ApiETHTransactionRequest;
@class ApiETHTransactionResponse;
@class ApiEstimateEthGasPriceRequest;
@class ApiEstimateEthGasPriceResponse;
@class ApiEstimateEthGasRequest;
@class ApiEstimateEthGasResponse;
@class ApiEstimateTransactionSizeRequest;
@class ApiEstimateTransactionSizeResponse;
@class ApiExportPrivateKeyFromMasterRequest;
@class ApiExportPrivateKeyFromMasterResponse;
@class ApiExportPrivateKeyRequest;
@class ApiExportPrivateKeyResponse;
@class ApiFindMnemonicRequest;
@class ApiFindMnemonicResponse;
@class ApiGetAddressBalanceRequest;
@class ApiGetAddressBalanceResponse;
@class ApiGetAddressesTxIdsRequest;
@class ApiGetAddressesTxIdsResponse;
@class ApiGetBlockHeaderRequest;
@class ApiGetBlockHeaderResponse;
@class ApiGetBtcTransactionRequest;
@class ApiGetBtcTransactionResponse;
@class ApiImportPrivateKeyRequest;
@class ApiImportPrivateKeyResponse;
@class ApiImportWalletFromMnemonicRequest;
@class ApiImportWalletFromMnemonicResponse;
@class ApiInterface;
@class ApiInterfaces;
@class ApiModifyPasswordRequest;
@class ApiModifyPasswordResponse;
@class ApiParamRequest;
@class ApiParamResponse;
@class ApiQueryBtcTransactionRequest;
@class ApiQueryBtcTransactionResponse;
@class ApiQueryETHTransactionRequest;
@class ApiQueryETHTransactionResponse;
@class ApiQueryTrxTransactionRequest;
@class ApiQueryTrxTransactionResponse;
@class ApiRemoveKeyRequest;
@class ApiRemoveKeyResponse;
@class ApiRemoveWalletRequest;
@class ApiRemoveWalletResponse;
@class ApiStrings;
@class ApiToTrxAddressRequest;
@class ApiToTrxAddressResponse;
@class ApiTransactionFeeRateRequest;
@class ApiTransactionFeeRateResponse;
@class ApiTransferFromHdWalletRequest;
@class ApiTransferFromHdWalletResponse;
@class ApiTransferRequest;
@class ApiTransferResponse;
@class ApiTrxContract;
@class ApiTrxParameter;
@class ApiTrxRawData;
@class ApiTrxRet;
@class ApiTrxTransaction;
@class ApiTrxTxInfo;
@class ApiTrxValue;
@class ApiValidateAddressRequest;
@class ApiValidateAddressResponse;
@class ApiVerifyMnemonicRequest;
@class ApiVerifyMnemonicResponse;
@class ApiVerifyMultiMnemonicRequest;
@class ApiVerifyMultiMnemonicResponse;
@class ApiVerifyWalletPasswordRequest;
@class ApiVerifyWalletPasswordResponse;
@protocol ApiAddCoinTypeCallback;
@class ApiAddCoinTypeCallback;
@protocol ApiAecoSignCallback;
@class ApiAecoSignCallback;
@protocol ApiBackupMnemonicCallback;
@class ApiBackupMnemonicCallback;
@protocol ApiCreateMnemonicCallback;
@class ApiCreateMnemonicCallback;
@protocol ApiCreateWalletCallback;
@class ApiCreateWalletCallback;
@protocol ApiEstimateEthGasPriceCallback;
@class ApiEstimateEthGasPriceCallback;
@protocol ApiEstimateTransactionSizeCallback;
@class ApiEstimateTransactionSizeCallback;
@protocol ApiExportPrivateKeyCallback;
@class ApiExportPrivateKeyCallback;
@protocol ApiFindMnemonicCallback;
@class ApiFindMnemonicCallback;
@protocol ApiGetAddressBalanceCallback;
@class ApiGetAddressBalanceCallback;
@protocol ApiGetAddressesTxIdsCallback;
@class ApiGetAddressesTxIdsCallback;
@protocol ApiGetBlockHeaderCallback;
@class ApiGetBlockHeaderCallback;
@protocol ApiGetBtcTransactionCallback;
@class ApiGetBtcTransactionCallback;
@protocol ApiImportPrivateKeyCallback;
@class ApiImportPrivateKeyCallback;
@protocol ApiImportWalletFromMnemonicCallback;
@class ApiImportWalletFromMnemonicCallback;
@protocol ApiModifyPasswordCallback;
@class ApiModifyPasswordCallback;
@protocol ApiParamCallback;
@class ApiParamCallback;
@protocol ApiQueryBtcTransactionCallback;
@class ApiQueryBtcTransactionCallback;
@protocol ApiRemoveKeyCallback;
@class ApiRemoveKeyCallback;
@protocol ApiRemoveWalletCallback;
@class ApiRemoveWalletCallback;
@protocol ApiTransactionFeeRateCallback;
@class ApiTransactionFeeRateCallback;
@protocol ApiTransferCallback;
@class ApiTransferCallback;
@protocol ApiValidateAddressCallback;
@class ApiValidateAddressCallback;
@protocol ApiVerifyMnemonicCallback;
@class ApiVerifyMnemonicCallback;
@protocol ApiVerifyMultiMnemonicCallback;
@class ApiVerifyMultiMnemonicCallback;

@protocol ApiAddCoinTypeCallback <NSObject>
- (void)failure:(NSError* _Nullable)err;
- (void)onProgress:(NSString* _Nullable)keyId walletId:(NSString* _Nullable)walletId coinType:(NSString* _Nullable)coinType address:(NSString* _Nullable)address;
- (void)success:(ApiAddCoinTypesResponse* _Nullable)p0;
@end

@protocol ApiAecoSignCallback <NSObject>
- (void)failure:(NSError* _Nullable)err;
- (void)success:(ApiAecoSignResponse* _Nullable)p0;
@end

@protocol ApiBackupMnemonicCallback <NSObject>
- (void)failure:(NSError* _Nullable)err;
- (void)success:(ApiBackupMnemonicResponse* _Nullable)p0;
@end

@protocol ApiCreateMnemonicCallback <NSObject>
- (void)failure:(NSError* _Nullable)err;
- (void)success:(ApiCreateMnemonicResponse* _Nullable)p0;
@end

@protocol ApiCreateWalletCallback <NSObject>
- (void)failure:(NSError* _Nullable)err;
- (void)onProgress:(NSString* _Nullable)keyId walletId:(NSString* _Nullable)walletId coinType:(NSString* _Nullable)coinType address:(NSString* _Nullable)address;
- (void)success:(ApiCreateWalletResponse* _Nullable)p0;
@end

@protocol ApiEstimateEthGasPriceCallback <NSObject>
- (void)failure:(NSError* _Nullable)err;
- (void)success:(ApiEstimateEthGasPriceResponse* _Nullable)p0;
@end

@protocol ApiEstimateTransactionSizeCallback <NSObject>
- (void)failure:(NSError* _Nullable)err;
- (void)success:(ApiEstimateTransactionSizeResponse* _Nullable)p0;
@end

@protocol ApiExportPrivateKeyCallback <NSObject>
- (void)failure:(NSError* _Nullable)err;
- (void)success:(ApiExportPrivateKeyResponse* _Nullable)p0;
@end

@protocol ApiFindMnemonicCallback <NSObject>
- (void)failure:(NSError* _Nullable)err;
- (void)success:(ApiFindMnemonicResponse* _Nullable)p0;
@end

@protocol ApiGetAddressBalanceCallback <NSObject>
- (void)failure:(NSError* _Nullable)err;
- (void)success:(ApiGetAddressBalanceResponse* _Nullable)p0;
@end

@protocol ApiGetAddressesTxIdsCallback <NSObject>
- (void)failure:(NSError* _Nullable)err;
- (void)success:(ApiGetAddressesTxIdsResponse* _Nullable)p0;
@end

@protocol ApiGetBlockHeaderCallback <NSObject>
- (void)failure:(NSError* _Nullable)err;
- (void)success:(ApiGetBlockHeaderResponse* _Nullable)p0;
@end

@protocol ApiGetBtcTransactionCallback <NSObject>
- (void)failure:(NSError* _Nullable)err;
- (void)success:(ApiGetBtcTransactionResponse* _Nullable)p0;
@end

@protocol ApiImportPrivateKeyCallback <NSObject>
- (void)failure:(NSError* _Nullable)err;
- (void)success:(ApiImportPrivateKeyResponse* _Nullable)p0;
@end

@protocol ApiImportWalletFromMnemonicCallback <NSObject>
- (void)failure:(NSError* _Nullable)err;
- (void)onProgress:(NSString* _Nullable)keyId walletId:(NSString* _Nullable)walletId coinType:(NSString* _Nullable)coinType address:(NSString* _Nullable)address;
- (void)success:(ApiImportWalletFromMnemonicResponse* _Nullable)p0;
@end

@protocol ApiModifyPasswordCallback <NSObject>
- (void)failure:(NSError* _Nullable)err;
- (void)onProgress:(NSString* _Nullable)keyId walletId:(NSString* _Nullable)walletId;
- (void)success:(ApiModifyPasswordResponse* _Nullable)p0;
@end

@protocol ApiParamCallback <NSObject>
- (void)failure:(NSError* _Nullable)err;
- (void)success:(ApiParamResponse* _Nullable)p0;
@end

@protocol ApiQueryBtcTransactionCallback <NSObject>
- (void)failure:(NSError* _Nullable)err;
- (void)success:(ApiQueryBtcTransactionResponse* _Nullable)p0;
@end

@protocol ApiRemoveKeyCallback <NSObject>
- (void)failure:(NSError* _Nullable)err;
- (void)onProgress:(NSString* _Nullable)keyId;
- (void)success:(ApiRemoveKeyResponse* _Nullable)p0;
@end

@protocol ApiRemoveWalletCallback <NSObject>
- (void)failure:(NSError* _Nullable)err;
- (void)onProgress:(NSString* _Nullable)keyId walletId:(NSString* _Nullable)walletId;
- (void)success:(ApiRemoveWalletResponse* _Nullable)p0;
@end

@protocol ApiTransactionFeeRateCallback <NSObject>
- (void)failure:(NSError* _Nullable)err;
- (void)success:(ApiTransactionFeeRateResponse* _Nullable)p0;
@end

@protocol ApiTransferCallback <NSObject>
- (void)failure:(NSError* _Nullable)err;
- (void)success:(ApiTransferResponse* _Nullable)p0;
@end

@protocol ApiValidateAddressCallback <NSObject>
- (void)failure:(NSError* _Nullable)err;
- (void)success:(ApiValidateAddressResponse* _Nullable)p0;
@end

@protocol ApiVerifyMnemonicCallback <NSObject>
- (void)failure:(NSError* _Nullable)err;
- (void)success:(ApiVerifyMnemonicResponse* _Nullable)p0;
@end

@protocol ApiVerifyMultiMnemonicCallback <NSObject>
- (void)failure:(NSError* _Nullable)err;
- (void)success:(ApiVerifyMultiMnemonicResponse* _Nullable)p0;
@end

/**
 * 增加一个多链钱包主币种
 */
@interface ApiAddCoinTypeRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull walletId;
@property (nonatomic) NSString* _Nonnull keystoreDir;
@property (nonatomic) NSString* _Nonnull keystorePassword;
@property (nonatomic) NSString* _Nonnull coinType;
@end

@interface ApiAddCoinTypeResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) int64_t coin;
@property (nonatomic) int64_t account;
@property (nonatomic) int64_t change;
@property (nonatomic) int64_t index;
@property (nonatomic) NSString* _Nonnull address;
@end

/**
 * 增加多链钱包主币种
 */
@interface ApiAddCoinTypesRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull walletId;
@property (nonatomic) NSString* _Nonnull keystoreDir;
@property (nonatomic) NSString* _Nonnull keystorePassword;
@property (nonatomic) NSString* _Nonnull coinTypes;
@end

@interface ApiAddCoinTypesResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull keyIds;
@end

@interface ApiAecoSignRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull keystoreDir;
@property (nonatomic) NSString* _Nonnull password;
@property (nonatomic) NSString* _Nonnull address;
@property (nonatomic) NSData* _Nullable data;
@property (nonatomic) NSString* _Nonnull keyId;
@end

@interface ApiAecoSignRequestFromMaster : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull keystoreDir;
@property (nonatomic) NSString* _Nonnull password;
@property (nonatomic) NSString* _Nonnull address;
@property (nonatomic) NSData* _Nullable data;
@property (nonatomic) int64_t coin;
@property (nonatomic) int64_t account;
@property (nonatomic) int64_t change;
@property (nonatomic) int64_t index;
@property (nonatomic) NSString* _Nonnull walletId;
@end

@interface ApiAecoSignResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull address;
@property (nonatomic) NSString* _Nonnull data;
@property (nonatomic) NSString* _Nonnull signedData;
@end

@interface ApiAecoSignResponseFromMaster : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull address;
@property (nonatomic) NSString* _Nonnull data;
@property (nonatomic) NSString* _Nonnull signedData;
@end

/**
 * 备份助记词
 */
@interface ApiBackupMnemonicRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull walletId;
@property (nonatomic) NSString* _Nonnull keystoreDir;
@property (nonatomic) NSString* _Nonnull keystorePassword;
@end

@interface ApiBackupMnemonicResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull mnemonics;
@end

/**
 * A BigInt represents a signed multi-precision integer.
 */
@interface ApiBigInt : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewBigInt allocates and returns a new BigInt set to x.
 */
- (nullable instancetype)init:(int64_t)x;
/**
 * NewBigIntFromString allocates and returns a new BigInt set to x
interpreted in the provided base.
 */
- (nullable instancetype)initFromString:(NSString* _Nullable)x base:(long)base;
/**
 * GetBytes returns the absolute value of x as a big-endian byte slice.
 */
- (NSData* _Nullable)getBytes;
/**
 * GetInt64 returns the int64 representation of x. If x cannot be represented in
an int64, the result is undefined.
 */
- (int64_t)getInt64;
/**
 * GetString returns the value of x as a formatted string in some number base.
 */
- (NSString* _Nonnull)getString:(long)base;
/**
 * SetBytes interprets buf as the bytes of a big-endian unsigned integer and sets
the big int to that value.
 */
- (void)setBytes:(NSData* _Nullable)buf;
/**
 * SetInt64 sets the big int to x.
 */
- (void)setInt64:(int64_t)x;
/**
 * SetString sets the big int to x.

The string prefix determines the actual conversion base. A prefix of "0x" or
"0X" selects base 16; the "0" prefix selects base 8, and a "0b" or "0B" prefix
selects base 2. Otherwise the selected base is 10.
 */
- (void)setString:(NSString* _Nullable)x base:(long)base;
/**
 * Sign returns:

	-1 if x <  0
	 0 if x == 0
	+1 if x >  0
 */
- (long)sign;
/**
 * String returns the value of x as a formatted decimal string.
 */
- (NSString* _Nonnull)string;
@end

/**
 * BigInts represents a slice of big ints.
 */
@interface ApiBigInts : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewBigInts creates a slice of uninitialized big numbers.
 */
- (nullable instancetype)init:(long)size;
/**
 * Get returns the bigint at the given index from the slice.
 */
- (ApiBigInt* _Nullable)get:(long)index error:(NSError* _Nullable* _Nullable)error;
/**
 * Set sets the big int at the given index in the slice.
 */
- (BOOL)set:(long)index bigint:(ApiBigInt* _Nullable)bigint error:(NSError* _Nullable* _Nullable)error;
/**
 * Size returns the number of big ints in the slice.
 */
- (long)size;
@end

/**
 * Binaries represents a slice of byte slice
 */
@interface ApiBinaries : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * Get returns the byte slice at the given index from the slice.
 */
- (NSData* _Nullable)get:(long)index error:(NSError* _Nullable* _Nullable)error;
/**
 * Set sets the byte slice at the given index in the slice.
 */
- (BOOL)set:(long)index binary:(NSData* _Nullable)binary error:(NSError* _Nullable* _Nullable)error;
/**
 * Size returns the number of byte slice in the slice.
 */
- (long)size;
/**
 * String implements the Stringer interface.
 */
- (NSString* _Nonnull)string;
@end

/**
 * Bools represents a slice of bool.
 */
@interface ApiBools : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * Get returns the bool at the given index from the slice.
 */
- (BOOL)get:(long)index b:(BOOL* _Nullable)b error:(NSError* _Nullable* _Nullable)error;
/**
 * Set sets the bool at the given index in the slice.
 */
- (BOOL)set:(long)index b:(BOOL)b error:(NSError* _Nullable* _Nullable)error;
/**
 * Size returns the number of bool in the slice.
 */
- (long)size;
/**
 * String implements the Stringer interface.
 */
- (NSString* _Nonnull)string;
@end

/**
 * 创建助记词
 */
@interface ApiCreateMnemonicRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) long length;
@end

@interface ApiCreateMnemonicResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull mnemonics;
@end

/**
 * 生成新的钱包
	KeystoreDir      string //keystore目录
	KeystorePassword string //密码
	CoinTypes        string //需要生成的币种列表 BTC ETH TAF...
	Force            bool   //是否强制导入,强制导入会覆盖以前的
 */
@interface ApiCreateWalletRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull keystoreDir;
@property (nonatomic) NSString* _Nonnull keystorePassword;
@property (nonatomic) NSString* _Nonnull coinTypes;
@property (nonatomic) BOOL force;
@end

@interface ApiCreateWalletResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull walletId;
@end

/**
 * 转换地址
 */
@interface ApiETHEipAddressRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull address;
@end

@interface ApiETHEipAddressResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull address;
@end

/**
 * 发送ETH交易
 */
@interface ApiETHTransactionRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull keystoreDir;
@property (nonatomic) NSString* _Nonnull keyId;
@property (nonatomic) int64_t coin;
@property (nonatomic) int64_t account;
@property (nonatomic) int64_t change;
@property (nonatomic) int64_t index;
@property (nonatomic) NSString* _Nonnull passphrase;
@property (nonatomic) NSString* _Nonnull fromAddress;
@property (nonatomic) NSString* _Nonnull toAddress;
@property (nonatomic) NSString* _Nonnull amount;
@property (nonatomic) int64_t gasLimit;
@property (nonatomic) NSString* _Nonnull data;
@end

@interface ApiETHTransactionResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull txId;
@property (nonatomic) NSString* _Nonnull keyId;
@property (nonatomic) NSString* _Nonnull nonce;
@end

/**
 * 预估Gas Price
 */
@interface ApiEstimateEthGasPriceRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@end

@interface ApiEstimateEthGasPriceResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull feeRate;
@end

/**
 * 计算gaslimit
 */
@interface ApiEstimateEthGasRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull from;
@property (nonatomic) NSString* _Nonnull to;
@property (nonatomic) NSString* _Nonnull data;
@end

@interface ApiEstimateEthGasResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) long gasLimit;
@end

/**
 * 根据交易ID查询交易
 */
@interface ApiEstimateTransactionSizeRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull address;
@end

@interface ApiEstimateTransactionSizeResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) long size;
@end

/**
 * 导出私钥 多链钱包 单链用ExportPrivateKeyRequest
 */
@interface ApiExportPrivateKeyFromMasterRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull walletId;
@property (nonatomic) NSString* _Nonnull keystoreDir;
@property (nonatomic) NSString* _Nonnull passphrase;
@property (nonatomic) int64_t coin;
@property (nonatomic) int64_t account;
@property (nonatomic) int64_t change;
@property (nonatomic) int64_t index;
@end

@interface ApiExportPrivateKeyFromMasterResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull privateKey;
@end

/**
 * 导出私钥 单链私钥 多链钱包用ExportPrivateKeyFromMasterRequest
 */
@interface ApiExportPrivateKeyRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull keyId;
@property (nonatomic) NSString* _Nonnull keystoreDir;
@property (nonatomic) NSString* _Nonnull passphrase;
@property (nonatomic) NSString* _Nonnull coinType;
@end

@interface ApiExportPrivateKeyResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull privateKey;
@end

/**
 * 查找助记词,根据前缀匹配
 */
@interface ApiFindMnemonicRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull prefix;
@end

@interface ApiFindMnemonicResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull mnemonic;
@end

/**
 * 查询地址对应余额
 */
@interface ApiGetAddressBalanceRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull coinType;
@property (nonatomic) NSString* _Nonnull tokenType;
@property (nonatomic) NSString* _Nonnull address;
@property (nonatomic) NSString* _Nonnull tokenAddress;
@end

@interface ApiGetAddressBalanceResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull coinType;
@property (nonatomic) NSString* _Nonnull tokenType;
@property (nonatomic) NSString* _Nonnull address;
@property (nonatomic) NSString* _Nonnull balanceAmount;
@end

/**
 * Addresses 数组 "1AMHv5kQ2gG5mLUbhhpLErjuuhk1r53tJ2","n1bnMC2FRtbupLLWrJWHp1XfLUSHnDBrmb"
 */
@interface ApiGetAddressesTxIdsRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull addresses;
@property (nonatomic) NSString* _Nonnull coinType;
@property (nonatomic) NSString* _Nonnull tokenType;
@property (nonatomic) int64_t startHeight;
@end

/**
 * TxIds 数组 "0e60fd547b6e0e7e28fe778c6db1d025ded6ed032d77d28cf57aa0b3f9add97f","8023fc46e05fee766ec25863e38ff52a43481088bfa2689e01cc2a2e358fdcd4"
 */
@interface ApiGetAddressesTxIdsResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull txIds;
@property (nonatomic) NSString* _Nonnull coinType;
@property (nonatomic) NSString* _Nonnull tokenType;
@end

/**
 * 获取区块头信息
Arguments:
1. blockhash    (string, required) The block hash

Result
  "hash" : "hash",     (string) the block hash (same as provided)
  "confirmations" : n,   (numeric) The number of confirmations, or -1 if the block is not on the main chain
  "height" : n,          (numeric) The block height or index
  "version" : n,         (numeric) The block version
  "versionHex" : "00000000", (string) The block version formatted in hexadecimal
  "merkleroot" : "xxxx", (string) The merkle root
  "time" : ttt,          (numeric) The block time in seconds since epoch (Jan 1 1970 GMT)
  "mediantime" : ttt,    (numeric) The median block time in seconds since epoch (Jan 1 1970 GMT)
  "nonce" : n,           (numeric) The nonce
  "bits" : "1d00ffff", (string) The bits
  "difficulty" : x.xxx,  (numeric) The difficulty
  "chainwork" : "0000...1f3"     (string) Expected number of hashes required to produce the current chain (in hex)
  "nTx" : n,             (numeric) The number of transactions in the block.
  "previousblockhash" : "hash",  (string) The hash of the previous block
  "nextblockhash" : "hash",      (string) The hash of the next block
 */
@interface ApiGetBlockHeaderRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull blockHash;
@end

@interface ApiGetBlockHeaderResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull hash;
@property (nonatomic) NSString* _Nonnull confirmations;
@property (nonatomic) NSString* _Nonnull height;
@property (nonatomic) NSString* _Nonnull version;
@property (nonatomic) NSString* _Nonnull versionHex;
@property (nonatomic) NSString* _Nonnull merkleRoot;
@property (nonatomic) int64_t time;
@property (nonatomic) int64_t medianTime;
@property (nonatomic) int64_t nonce;
@property (nonatomic) NSString* _Nonnull bits;
@property (nonatomic) NSString* _Nonnull difficulty;
@property (nonatomic) NSString* _Nonnull chainWork;
@property (nonatomic) int64_t ntx;
@property (nonatomic) NSString* _Nonnull previousBlockHash;
@property (nonatomic) NSString* _Nonnull nextBlockHash;
@end

/**
 * *
获取比特币钱包交易
 */
@interface ApiGetBtcTransactionRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull txid;
@end

@interface ApiGetBtcTransactionResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull txid;
// skipped field GetBtcTransactionResponse.Amount with unsupported type: encoding/json.Number

// skipped field GetBtcTransactionResponse.Fee with unsupported type: encoding/json.Number

@property (nonatomic) NSString* _Nonnull blockhash;
@property (nonatomic) int64_t blockindex;
@property (nonatomic) int64_t blocktime;
@property (nonatomic) int64_t time;
@property (nonatomic) int64_t timereceived;
@property (nonatomic) NSString* _Nonnull bip125Replaceable;
@property (nonatomic) NSString* _Nonnull hex;
@property (nonatomic) BOOL trusted;
@property (nonatomic) int64_t confirmations;
// skipped field GetBtcTransactionResponse.Walletconflicts with unsupported type: []string

@end

/**
 * 导入私钥
 */
@interface ApiImportPrivateKeyRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull coinType;
@property (nonatomic) NSString* _Nonnull privateKey;
@property (nonatomic) NSString* _Nonnull keystoreDir;
@property (nonatomic) NSString* _Nonnull passphrase;
@property (nonatomic) BOOL force;
@end

@interface ApiImportPrivateKeyResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull keyId;
@property (nonatomic) NSString* _Nonnull address;
@end

/**
 * 通过助记词导入,生成新的钱包,并生成对应币种的私钥
KeystoreDir      string //keystore目录
KeystorePassword string //密码
Mnemonics        string //助记词,用空格分割
CoinTypes        string //需要生成的币种列表 BTC ETH TAF...
Force            bool   //是否强制导入,强制导入会覆盖以前的
 */
@interface ApiImportWalletFromMnemonicRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull keystoreDir;
@property (nonatomic) NSString* _Nonnull keystorePassword;
@property (nonatomic) NSString* _Nonnull mnemonics;
@property (nonatomic) NSString* _Nonnull coinTypes;
@property (nonatomic) BOOL force;
@end

@interface ApiImportWalletFromMnemonicResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull walletId;
@end

/**
 * Interface represents a wrapped version of Go's interface{}, with the capacity
to store arbitrary data types.

Since it's impossible to get the arbitrary-ness converted between Go and mobile
platforms, we're using explicit getters and setters for the conversions. There
is of course no point in enumerating everything, just enough to support the
contract bindins requiring client side generated code.
 */
@interface ApiInterface : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewInterface creates a new empty interface that can be used to pass around
generic types.
 */
- (nullable instancetype)init;
- (ApiBigInt* _Nullable)getBigInt;
- (ApiBigInts* _Nullable)getBigInts;
- (ApiBinaries* _Nullable)getBinaries;
- (NSData* _Nullable)getBinary;
- (BOOL)getBool;
- (ApiBools* _Nullable)getBools;
- (int16_t)getInt16;
- (ApiBigInts* _Nullable)getInt16s;
- (int32_t)getInt32;
- (ApiBigInts* _Nullable)getInt32s;
- (int64_t)getInt64;
- (ApiBigInts* _Nullable)getInt64s;
- (int8_t)getInt8;
- (ApiBigInts* _Nullable)getInt8s;
- (NSString* _Nonnull)getString;
- (ApiStrings* _Nullable)getStrings;
- (ApiBigInt* _Nullable)getUint16;
- (ApiBigInts* _Nullable)getUint16s;
- (ApiBigInt* _Nullable)getUint32;
- (ApiBigInts* _Nullable)getUint32s;
- (ApiBigInt* _Nullable)getUint64;
- (ApiBigInts* _Nullable)getUint64s;
- (ApiBigInt* _Nullable)getUint8;
- (ApiBigInts* _Nullable)getUint8s;
- (void)setBigInt:(ApiBigInt* _Nullable)bigint;
- (void)setBigInts:(ApiBigInts* _Nullable)bigints;
- (void)setBinaries:(ApiBinaries* _Nullable)binaries;
- (void)setBinary:(NSData* _Nullable)binary;
- (void)setBool:(BOOL)b;
- (void)setBools:(ApiBools* _Nullable)bs;
- (void)setDefaultBigInt;
- (void)setDefaultBigInts;
- (void)setDefaultBinaries;
- (void)setDefaultBinary;
- (void)setDefaultBool;
- (void)setDefaultBools;
- (void)setDefaultInt16;
- (void)setDefaultInt16s;
- (void)setDefaultInt32;
- (void)setDefaultInt32s;
- (void)setDefaultInt64;
- (void)setDefaultInt64s;
- (void)setDefaultInt8;
- (void)setDefaultInt8s;
- (void)setDefaultString;
- (void)setDefaultStrings;
- (void)setDefaultUint16;
- (void)setDefaultUint16s;
- (void)setDefaultUint32;
- (void)setDefaultUint32s;
- (void)setDefaultUint64;
- (void)setDefaultUint64s;
- (void)setDefaultUint8;
- (void)setDefaultUint8s;
- (void)setInt16:(int16_t)n;
- (void)setInt16s:(ApiBigInts* _Nullable)bigints;
- (void)setInt32:(int32_t)n;
- (void)setInt32s:(ApiBigInts* _Nullable)bigints;
- (void)setInt64:(int64_t)n;
- (void)setInt64s:(ApiBigInts* _Nullable)bigints;
- (void)setInt8:(int8_t)n;
- (void)setInt8s:(ApiBigInts* _Nullable)bigints;
- (void)setString:(NSString* _Nullable)str;
- (void)setStrings:(ApiStrings* _Nullable)strs;
- (void)setUint16:(ApiBigInt* _Nullable)bigint;
- (void)setUint16s:(ApiBigInts* _Nullable)bigints;
- (void)setUint32:(ApiBigInt* _Nullable)bigint;
- (void)setUint32s:(ApiBigInts* _Nullable)bigints;
- (void)setUint64:(ApiBigInt* _Nullable)bigint;
- (void)setUint64s:(ApiBigInts* _Nullable)bigints;
- (void)setUint8:(ApiBigInt* _Nullable)bigint;
- (void)setUint8s:(ApiBigInts* _Nullable)bigints;
@end

/**
 * Interfaces is a slices of wrapped generic objects.
 */
@interface ApiInterfaces : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewInterfaces creates a slice of uninitialized interfaces.
 */
- (nullable instancetype)init:(long)size;
/**
 * Get returns the bigint at the given index from the slice.
Notably the returned value can be changed without affecting the
interfaces itself.
 */
- (ApiInterface* _Nullable)get:(long)index error:(NSError* _Nullable* _Nullable)error;
/**
 * Set sets the big int at the given index in the slice.
 */
- (BOOL)set:(long)index object:(ApiInterface* _Nullable)object error:(NSError* _Nullable* _Nullable)error;
/**
 * Size returns the number of interfaces in the slice.
 */
- (long)size;
@end

/**
 * 修改密码 KeyIds用逗号分割
 */
@interface ApiModifyPasswordRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull keystoreDir;
@property (nonatomic) NSString* _Nonnull walletId;
@property (nonatomic) NSString* _Nonnull keyIds;
@property (nonatomic) NSString* _Nonnull prevPassword;
@property (nonatomic) NSString* _Nonnull newPassword;
@end

@interface ApiModifyPasswordResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull walletId;
@end

/**
 * 获取SDK参数
主网 main, 测试网 testnet, 私有网 regtest
 */
@interface ApiParamRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull net;
@end

@interface ApiParamResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull net;
@property (nonatomic) NSString* _Nonnull httpUrl;
@property (nonatomic) NSString* _Nonnull verSion;
@end

/**
 * 根据txid查询交易
 */
@interface ApiQueryBtcTransactionRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull txId;
@end

@interface ApiQueryBtcTransactionResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull txId;
@property (nonatomic) NSString* _Nonnull amount;
@property (nonatomic) NSString* _Nonnull fee;
@property (nonatomic) NSString* _Nonnull blockHash;
@property (nonatomic) int64_t blockIndex;
@property (nonatomic) int64_t blockTime;
@property (nonatomic) int64_t time;
@property (nonatomic) int64_t timeReceived;
@property (nonatomic) NSString* _Nonnull bip125Replaceable;
@property (nonatomic) NSString* _Nonnull hex;
@end

@interface ApiQueryETHTransactionRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull txId;
@end

@interface ApiQueryETHTransactionResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) BOOL value;
@end

@interface ApiQueryTrxTransactionRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull txIds;
@end

@interface ApiQueryTrxTransactionResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull trxTransaction;
@end

/**
 * 删除指定私钥, KeyIds用逗号分割
 */
@interface ApiRemoveKeyRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull keystoreDir;
@property (nonatomic) NSString* _Nonnull keyIds;
@property (nonatomic) NSString* _Nonnull password;
@property (nonatomic) BOOL force;
@end

@interface ApiRemoveKeyResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull keyIds;
@end

/**
 * 删除钱包, KeyIds用逗号分割
 */
@interface ApiRemoveWalletRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull keystoreDir;
@property (nonatomic) NSString* _Nonnull walletId;
@property (nonatomic) NSString* _Nonnull keyIds;
@property (nonatomic) NSString* _Nonnull password;
@property (nonatomic) BOOL force;
@end

@interface ApiRemoveWalletResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull walletId;
@property (nonatomic) NSString* _Nonnull keyIds;
@end

/**
 * Strings represents s slice of strs.
 */
@interface ApiStrings : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * Get returns the string at the given index from the slice.
 */
- (NSString* _Nonnull)get:(long)index error:(NSError* _Nullable* _Nullable)error;
/**
 * Set sets the string at the given index in the slice.
 */
- (BOOL)set:(long)index str:(NSString* _Nullable)str error:(NSError* _Nullable* _Nullable)error;
/**
 * Size returns the number of strs in the slice.
 */
- (long)size;
/**
 * String implements the Stringer interface.
 */
- (NSString* _Nonnull)string;
@end

/**
 * 转换地址
 */
@interface ApiToTrxAddressRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull address;
@end

@interface ApiToTrxAddressResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull address;
@end

/**
 * 查询比特币矿工费率
 */
@interface ApiTransactionFeeRateRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull coinType;
@end

@interface ApiTransactionFeeRateResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) int64_t fastestFee;
@property (nonatomic) int64_t halfHourFee;
@property (nonatomic) int64_t hourFee;
@end

/**
 * 从多链钱包转账
 */
@interface ApiTransferFromHdWalletRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) ApiTransferRequest* _Nullable transferRequest;
@property (nonatomic) int64_t coin;
@property (nonatomic) int64_t account;
@property (nonatomic) int64_t change;
@property (nonatomic) int64_t index;
@end

@interface ApiTransferFromHdWalletResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) ApiTransferResponse* _Nullable transferResponse;
@end

/**
 * 转账
FeeRate 比特币费率 以太坊GasPrice
GasLimit 合约设置的GasLimit值
KeyId 注意 单链是keyId 多链是walletId
 */
@interface ApiTransferRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull coinType;
@property (nonatomic) NSString* _Nonnull tokenType;
@property (nonatomic) NSString* _Nonnull keystoreDir;
@property (nonatomic) NSString* _Nonnull keyId;
@property (nonatomic) NSString* _Nonnull toAddress;
@property (nonatomic) NSString* _Nonnull amount;
@property (nonatomic) NSString* _Nonnull passphrase;
@property (nonatomic) NSString* _Nonnull feeRate;
@property (nonatomic) int64_t gasLimit;
@property (nonatomic) NSString* _Nonnull tokenAddress;
@property (nonatomic) NSString* _Nonnull nonce;
@end

@interface ApiTransferResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull txId;
@property (nonatomic) NSString* _Nonnull coinType;
@property (nonatomic) NSString* _Nonnull tokenType;
@property (nonatomic) NSString* _Nonnull keyId;
@property (nonatomic) NSString* _Nonnull nonce;
@end

@interface ApiTrxContract : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field TrxContract.Parameter with unsupported type: vbh/taf-wallet/api.TrxParameter

@property (nonatomic) NSString* _Nonnull type;
@end

@interface ApiTrxParameter : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field TrxParameter.Value with unsupported type: vbh/taf-wallet/api.TrxValue

@property (nonatomic) NSString* _Nonnull typeUrl;
@end

@interface ApiTrxRawData : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field TrxRawData.Contract with unsupported type: []vbh/taf-wallet/api.TrxContract

@property (nonatomic) NSString* _Nonnull refBlockBytes;
@property (nonatomic) NSString* _Nonnull refBlockHash;
@property (nonatomic) int64_t expiration;
@property (nonatomic) int64_t feeLimit;
@property (nonatomic) int64_t timestamp;
@end

@interface ApiTrxRet : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull contractRet;
@end

@interface ApiTrxTransaction : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull txid;
// skipped field TrxTransaction.Ret with unsupported type: []vbh/taf-wallet/api.TrxRet

// skipped field TrxTransaction.Signature with unsupported type: []string

// skipped field TrxTransaction.RawData with unsupported type: vbh/taf-wallet/api.TrxRawData

@property (nonatomic) NSString* _Nonnull rawDataHex;
@end

@interface ApiTrxTxInfo : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull txId;
@property (nonatomic) NSString* _Nonnull from;
@property (nonatomic) NSString* _Nonnull to;
@property (nonatomic) NSString* _Nonnull contractAddress;
@property (nonatomic) NSString* _Nonnull amount;
@property (nonatomic) NSString* _Nonnull data;
@property (nonatomic) NSString* _Nonnull blockNumber;
@property (nonatomic) NSString* _Nonnull blockTime;
@property (nonatomic) NSString* _Nonnull fee;
@property (nonatomic) NSString* _Nonnull result;
@end

@interface ApiTrxValue : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull data;
@property (nonatomic) NSString* _Nonnull ownerAddress;
@property (nonatomic) NSString* _Nonnull toAddress;
@property (nonatomic) NSString* _Nonnull contractAddress;
@property (nonatomic) int64_t amount;
@end

/**
 * 验证地址是否合法
 */
@interface ApiValidateAddressRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull address;
@property (nonatomic) NSString* _Nonnull coinType;
@end

@interface ApiValidateAddressResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) BOOL valid;
@end

/**
 * 验证助记词是否合法
 */
@interface ApiVerifyMnemonicRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull word;
@end

@interface ApiVerifyMnemonicResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) BOOL valid;
@end

/**
 * 验证多个助记词有效性
 */
@interface ApiVerifyMultiMnemonicRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull word;
@end

@interface ApiVerifyMultiMnemonicResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull invalidWord;
@property (nonatomic) NSString* _Nonnull validWord;
@end

/**
 * 校验密码有效性 true有效 false无效
 */
@interface ApiVerifyWalletPasswordRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull walletId;
@property (nonatomic) NSString* _Nonnull keystoreDir;
@property (nonatomic) NSString* _Nonnull password;
@end

@interface ApiVerifyWalletPasswordResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) BOOL valid;
@end

/**
 * 可用余额不足
 */
FOUNDATION_EXPORT NSString* _Nonnull const ApiAvailablefundsErr;
/**
 * BTC费率查询超时
 */
FOUNDATION_EXPORT NSString* _Nonnull const ApiBtcFeeTimeOutErr;
/**
 * 旷工费不够
 */
FOUNDATION_EXPORT NSString* _Nonnull const ApiInsufficientErr;
/**
 * BTC交易查询报错，没出快导致交易没有上链
 */
FOUNDATION_EXPORT NSString* _Nonnull const ApiNoWalletTxidErr;
/**
 * nonce值错误
 */
FOUNDATION_EXPORT NSString* _Nonnull const ApiNonceErr;
FOUNDATION_EXPORT NSString* _Nonnull const ApiTxnsPrematureSpendOfCoinbaseErr;

/**
 * NewBigInt allocates and returns a new BigInt set to x.
 */
FOUNDATION_EXPORT ApiBigInt* _Nullable ApiNewBigInt(int64_t x);

/**
 * NewBigIntFromString allocates and returns a new BigInt set to x
interpreted in the provided base.
 */
FOUNDATION_EXPORT ApiBigInt* _Nullable ApiNewBigIntFromString(NSString* _Nullable x, long base);

/**
 * NewBigInts creates a slice of uninitialized big numbers.
 */
FOUNDATION_EXPORT ApiBigInts* _Nullable ApiNewBigInts(long size);

/**
 * NewInterface creates a new empty interface that can be used to pass around
generic types.
 */
FOUNDATION_EXPORT ApiInterface* _Nullable ApiNewInterface(void);

/**
 * NewInterfaces creates a slice of uninitialized interfaces.
 */
FOUNDATION_EXPORT ApiInterfaces* _Nullable ApiNewInterfaces(long size);

@class ApiAddCoinTypeCallback;

@class ApiAecoSignCallback;

@class ApiBackupMnemonicCallback;

@class ApiCreateMnemonicCallback;

@class ApiCreateWalletCallback;

@class ApiEstimateEthGasPriceCallback;

@class ApiEstimateTransactionSizeCallback;

@class ApiExportPrivateKeyCallback;

@class ApiFindMnemonicCallback;

@class ApiGetAddressBalanceCallback;

@class ApiGetAddressesTxIdsCallback;

@class ApiGetBlockHeaderCallback;

@class ApiGetBtcTransactionCallback;

@class ApiImportPrivateKeyCallback;

@class ApiImportWalletFromMnemonicCallback;

@class ApiModifyPasswordCallback;

@class ApiParamCallback;

@class ApiQueryBtcTransactionCallback;

@class ApiRemoveKeyCallback;

@class ApiRemoveWalletCallback;

@class ApiTransactionFeeRateCallback;

@class ApiTransferCallback;

@class ApiValidateAddressCallback;

@class ApiVerifyMnemonicCallback;

@class ApiVerifyMultiMnemonicCallback;

@interface ApiAddCoinTypeCallback : NSObject <goSeqRefInterface, ApiAddCoinTypeCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)failure:(NSError* _Nullable)err;
- (void)onProgress:(NSString* _Nullable)keyId walletId:(NSString* _Nullable)walletId coinType:(NSString* _Nullable)coinType address:(NSString* _Nullable)address;
- (void)success:(ApiAddCoinTypesResponse* _Nullable)p0;
@end

@interface ApiAecoSignCallback : NSObject <goSeqRefInterface, ApiAecoSignCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)failure:(NSError* _Nullable)err;
- (void)success:(ApiAecoSignResponse* _Nullable)p0;
@end

@interface ApiBackupMnemonicCallback : NSObject <goSeqRefInterface, ApiBackupMnemonicCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)failure:(NSError* _Nullable)err;
- (void)success:(ApiBackupMnemonicResponse* _Nullable)p0;
@end

@interface ApiCreateMnemonicCallback : NSObject <goSeqRefInterface, ApiCreateMnemonicCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)failure:(NSError* _Nullable)err;
- (void)success:(ApiCreateMnemonicResponse* _Nullable)p0;
@end

@interface ApiCreateWalletCallback : NSObject <goSeqRefInterface, ApiCreateWalletCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)failure:(NSError* _Nullable)err;
- (void)onProgress:(NSString* _Nullable)keyId walletId:(NSString* _Nullable)walletId coinType:(NSString* _Nullable)coinType address:(NSString* _Nullable)address;
- (void)success:(ApiCreateWalletResponse* _Nullable)p0;
@end

@interface ApiEstimateEthGasPriceCallback : NSObject <goSeqRefInterface, ApiEstimateEthGasPriceCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)failure:(NSError* _Nullable)err;
- (void)success:(ApiEstimateEthGasPriceResponse* _Nullable)p0;
@end

@interface ApiEstimateTransactionSizeCallback : NSObject <goSeqRefInterface, ApiEstimateTransactionSizeCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)failure:(NSError* _Nullable)err;
- (void)success:(ApiEstimateTransactionSizeResponse* _Nullable)p0;
@end

@interface ApiExportPrivateKeyCallback : NSObject <goSeqRefInterface, ApiExportPrivateKeyCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)failure:(NSError* _Nullable)err;
- (void)success:(ApiExportPrivateKeyResponse* _Nullable)p0;
@end

@interface ApiFindMnemonicCallback : NSObject <goSeqRefInterface, ApiFindMnemonicCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)failure:(NSError* _Nullable)err;
- (void)success:(ApiFindMnemonicResponse* _Nullable)p0;
@end

@interface ApiGetAddressBalanceCallback : NSObject <goSeqRefInterface, ApiGetAddressBalanceCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)failure:(NSError* _Nullable)err;
- (void)success:(ApiGetAddressBalanceResponse* _Nullable)p0;
@end

@interface ApiGetAddressesTxIdsCallback : NSObject <goSeqRefInterface, ApiGetAddressesTxIdsCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)failure:(NSError* _Nullable)err;
- (void)success:(ApiGetAddressesTxIdsResponse* _Nullable)p0;
@end

@interface ApiGetBlockHeaderCallback : NSObject <goSeqRefInterface, ApiGetBlockHeaderCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)failure:(NSError* _Nullable)err;
- (void)success:(ApiGetBlockHeaderResponse* _Nullable)p0;
@end

@interface ApiGetBtcTransactionCallback : NSObject <goSeqRefInterface, ApiGetBtcTransactionCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)failure:(NSError* _Nullable)err;
- (void)success:(ApiGetBtcTransactionResponse* _Nullable)p0;
@end

@interface ApiImportPrivateKeyCallback : NSObject <goSeqRefInterface, ApiImportPrivateKeyCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)failure:(NSError* _Nullable)err;
- (void)success:(ApiImportPrivateKeyResponse* _Nullable)p0;
@end

@interface ApiImportWalletFromMnemonicCallback : NSObject <goSeqRefInterface, ApiImportWalletFromMnemonicCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)failure:(NSError* _Nullable)err;
- (void)onProgress:(NSString* _Nullable)keyId walletId:(NSString* _Nullable)walletId coinType:(NSString* _Nullable)coinType address:(NSString* _Nullable)address;
- (void)success:(ApiImportWalletFromMnemonicResponse* _Nullable)p0;
@end

@interface ApiModifyPasswordCallback : NSObject <goSeqRefInterface, ApiModifyPasswordCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)failure:(NSError* _Nullable)err;
- (void)onProgress:(NSString* _Nullable)keyId walletId:(NSString* _Nullable)walletId;
- (void)success:(ApiModifyPasswordResponse* _Nullable)p0;
@end

@interface ApiParamCallback : NSObject <goSeqRefInterface, ApiParamCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)failure:(NSError* _Nullable)err;
- (void)success:(ApiParamResponse* _Nullable)p0;
@end

@interface ApiQueryBtcTransactionCallback : NSObject <goSeqRefInterface, ApiQueryBtcTransactionCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)failure:(NSError* _Nullable)err;
- (void)success:(ApiQueryBtcTransactionResponse* _Nullable)p0;
@end

@interface ApiRemoveKeyCallback : NSObject <goSeqRefInterface, ApiRemoveKeyCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)failure:(NSError* _Nullable)err;
- (void)onProgress:(NSString* _Nullable)keyId;
- (void)success:(ApiRemoveKeyResponse* _Nullable)p0;
@end

@interface ApiRemoveWalletCallback : NSObject <goSeqRefInterface, ApiRemoveWalletCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)failure:(NSError* _Nullable)err;
- (void)onProgress:(NSString* _Nullable)keyId walletId:(NSString* _Nullable)walletId;
- (void)success:(ApiRemoveWalletResponse* _Nullable)p0;
@end

@interface ApiTransactionFeeRateCallback : NSObject <goSeqRefInterface, ApiTransactionFeeRateCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)failure:(NSError* _Nullable)err;
- (void)success:(ApiTransactionFeeRateResponse* _Nullable)p0;
@end

@interface ApiTransferCallback : NSObject <goSeqRefInterface, ApiTransferCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)failure:(NSError* _Nullable)err;
- (void)success:(ApiTransferResponse* _Nullable)p0;
@end

@interface ApiValidateAddressCallback : NSObject <goSeqRefInterface, ApiValidateAddressCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)failure:(NSError* _Nullable)err;
- (void)success:(ApiValidateAddressResponse* _Nullable)p0;
@end

@interface ApiVerifyMnemonicCallback : NSObject <goSeqRefInterface, ApiVerifyMnemonicCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)failure:(NSError* _Nullable)err;
- (void)success:(ApiVerifyMnemonicResponse* _Nullable)p0;
@end

@interface ApiVerifyMultiMnemonicCallback : NSObject <goSeqRefInterface, ApiVerifyMultiMnemonicCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)failure:(NSError* _Nullable)err;
- (void)success:(ApiVerifyMultiMnemonicResponse* _Nullable)p0;
@end

#endif
