// Objective-C API for talking to vbh/taf-wallet/sdk Go package.
//   gobind -lang=objc vbh/taf-wallet/sdk
//
// File is generated by gobind. Do not edit.

#ifndef __Sdk_H__
#define __Sdk_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"

#include "Api.objc.h"

@class SdkEthClient;

@interface SdkEthClient : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field EthClient.EthRPC with unsupported type: *vbh/taf-wallet/internal/eth/rpc.EthRPC

// skipped method EthClient.Call with unsupported parameter or return types

// skipped method EthClient.ChainID with unsupported parameter or return types

// skipped method EthClient.Eth1 with unsupported parameter or return types

// skipped method EthClient.EthAccounts with unsupported parameter or return types

- (BOOL)ethBlockNumber:(long* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
// skipped method EthClient.EthCall with unsupported parameter or return types

- (NSString* _Nonnull)ethCoinbase:(NSError* _Nullable* _Nullable)error;
- (BOOL)ethEstimateGas:(NSString* _Nullable)from to:(NSString* _Nullable)to data:(NSString* _Nullable)data ret0_:(long* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
// skipped method EthClient.EthGasPrice with unsupported parameter or return types

// skipped method EthClient.EthGetBalance with unsupported parameter or return types

// skipped method EthClient.EthGetBlockByHash with unsupported parameter or return types

// skipped method EthClient.EthGetBlockByNumber with unsupported parameter or return types

- (BOOL)ethGetBlockTransactionCountByHash:(NSString* _Nullable)hash ret0_:(long* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
- (BOOL)ethGetBlockTransactionCountByNumber:(long)number ret0_:(long* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)ethGetCode:(NSString* _Nullable)address block:(NSString* _Nullable)block error:(NSError* _Nullable* _Nullable)error;
// skipped method EthClient.EthGetCompilers with unsupported parameter or return types

// skipped method EthClient.EthGetFilterChanges with unsupported parameter or return types

// skipped method EthClient.EthGetFilterLogs with unsupported parameter or return types

// skipped method EthClient.EthGetLogs with unsupported parameter or return types

- (NSString* _Nonnull)ethGetStorageAt:(NSString* _Nullable)data position:(long)position tag:(NSString* _Nullable)tag error:(NSError* _Nullable* _Nullable)error;
// skipped method EthClient.EthGetTransactionByBlockHashAndIndex with unsupported parameter or return types

// skipped method EthClient.EthGetTransactionByBlockNumberAndIndex with unsupported parameter or return types

// skipped method EthClient.EthGetTransactionByHash with unsupported parameter or return types

- (BOOL)ethGetTransactionCount:(NSString* _Nullable)address block:(NSString* _Nullable)block ret0_:(long* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
// skipped method EthClient.EthGetTransactionReceipt with unsupported parameter or return types

- (BOOL)ethGetUncleCountByBlockHash:(NSString* _Nullable)hash ret0_:(long* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
- (BOOL)ethGetUncleCountByBlockNumber:(long)number ret0_:(long* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
- (BOOL)ethHashrate:(long* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
- (BOOL)ethMining:(BOOL* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)ethNewBlockFilter:(NSError* _Nullable* _Nullable)error;
// skipped method EthClient.EthNewFilter with unsupported parameter or return types

- (NSString* _Nonnull)ethNewPendingTransactionFilter:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)ethProtocolVersion:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)ethSendRawTransaction:(NSString* _Nullable)data error:(NSError* _Nullable* _Nullable)error;
// skipped method EthClient.EthSendTransaction with unsupported parameter or return types

- (NSString* _Nonnull)ethSign:(NSString* _Nullable)address data:(NSString* _Nullable)data error:(NSError* _Nullable* _Nullable)error;
// skipped method EthClient.EthSyncing with unsupported parameter or return types

- (BOOL)ethUninstallFilter:(NSString* _Nullable)filterID ret0_:(BOOL* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
- (BOOL)netListening:(BOOL* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
- (BOOL)netPeerCount:(long* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)netVersion:(NSError* _Nullable* _Nullable)error;
// skipped method EthClient.RawCall with unsupported parameter or return types

- (NSString* _Nonnull)url;
- (NSString* _Nonnull)web3ClientVersion:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)web3Sha3:(NSData* _Nullable)data error:(NSError* _Nullable* _Nullable)error;
@end

FOUNDATION_EXPORT NSString* _Nonnull const SdkImportLabel;

FOUNDATION_EXPORT void SdkAddCoinTypes(ApiAddCoinTypesRequest* _Nullable req, id<ApiAddCoinTypeCallback> _Nullable cb);

FOUNDATION_EXPORT void SdkBackupMnemonic(ApiBackupMnemonicRequest* _Nullable req, id<ApiBackupMnemonicCallback> _Nullable cb);

FOUNDATION_EXPORT void SdkCreateMnemonic(ApiCreateMnemonicRequest* _Nullable req, id<ApiCreateMnemonicCallback> _Nullable cb);

FOUNDATION_EXPORT void SdkCreateWallet(ApiCreateWalletRequest* _Nullable req, id<ApiCreateWalletCallback> _Nullable cb);

FOUNDATION_EXPORT void SdkEstimateEthGasPrice(ApiEstimateEthGasPriceRequest* _Nullable req, id<ApiEstimateEthGasPriceCallback> _Nullable cb);

FOUNDATION_EXPORT void SdkEstimateTransactionSize(ApiEstimateTransactionSizeRequest* _Nullable req, id<ApiEstimateTransactionSizeCallback> _Nullable cb);

FOUNDATION_EXPORT void SdkExportPrivateKey(ApiExportPrivateKeyRequest* _Nullable req, id<ApiExportPrivateKeyCallback> _Nullable cb);

FOUNDATION_EXPORT void SdkFindMnemonic(ApiFindMnemonicRequest* _Nullable req, id<ApiFindMnemonicCallback> _Nullable cb);

FOUNDATION_EXPORT void SdkGetAddressBalance(ApiGetAddressBalanceRequest* _Nullable req, id<ApiGetAddressBalanceCallback> _Nullable cb);

FOUNDATION_EXPORT void SdkGetAddressesTxIds(ApiGetAddressesTxIdsRequest* _Nullable req, id<ApiGetAddressesTxIdsCallback> _Nullable cb);

FOUNDATION_EXPORT void SdkGetBlockHeader(ApiGetBlockHeaderRequest* _Nullable req, id<ApiGetBlockHeaderCallback> _Nullable cb);

FOUNDATION_EXPORT void SdkGetBtcTransaction(ApiGetBtcTransactionRequest* _Nullable req, id<ApiGetBtcTransactionCallback> _Nullable cb);

FOUNDATION_EXPORT void SdkImportPrivateKey(ApiImportPrivateKeyRequest* _Nullable req, id<ApiImportPrivateKeyCallback> _Nullable cb);

FOUNDATION_EXPORT void SdkImportWalletFromMnemonic(ApiImportWalletFromMnemonicRequest* _Nullable req, id<ApiImportWalletFromMnemonicCallback> _Nullable cb);

FOUNDATION_EXPORT void SdkInitProd(void);

FOUNDATION_EXPORT void SdkInitReg(void);

FOUNDATION_EXPORT void SdkModifyPassword(ApiModifyPasswordRequest* _Nullable req, id<ApiModifyPasswordCallback> _Nullable cb);

FOUNDATION_EXPORT void SdkParamConfig(ApiParamRequest* _Nullable req, id<ApiParamCallback> _Nullable cb);

FOUNDATION_EXPORT void SdkQueryTransaction(ApiQueryBtcTransactionRequest* _Nullable req, id<ApiQueryBtcTransactionCallback> _Nullable cb);

FOUNDATION_EXPORT void SdkRemoveKey(ApiRemoveKeyRequest* _Nullable req, id<ApiRemoveKeyCallback> _Nullable cb);

FOUNDATION_EXPORT void SdkRemoveWallet(ApiRemoveWalletRequest* _Nullable req, id<ApiRemoveWalletCallback> _Nullable cb);

FOUNDATION_EXPORT void SdkSign(ApiAecoSignRequest* _Nullable req, id<ApiAecoSignCallback> _Nullable cb);

FOUNDATION_EXPORT void SdkTransactionFeeRate(ApiTransactionFeeRateRequest* _Nullable req, id<ApiTransactionFeeRateCallback> _Nullable cb);

FOUNDATION_EXPORT void SdkTransfer(ApiTransferRequest* _Nullable req, id<ApiTransferCallback> _Nullable cb);

FOUNDATION_EXPORT void SdkValidateAddress(ApiValidateAddressRequest* _Nullable req, id<ApiValidateAddressCallback> _Nullable cb);

FOUNDATION_EXPORT void SdkVerifyMnemonic(ApiVerifyMnemonicRequest* _Nullable req, id<ApiVerifyMnemonicCallback> _Nullable cb);

FOUNDATION_EXPORT void SdkVerifyMultiMnemonic(ApiVerifyMultiMnemonicRequest* _Nullable req, id<ApiVerifyMultiMnemonicCallback> _Nullable cb);

#endif
