// Objective-C API for talking to vbh/taf-wallet/sdk/v1 Go package.
//   gobind -lang=objc vbh/taf-wallet/sdk/v1
//
// File is generated by gobind. Do not edit.

#ifndef __Uv1_H__
#define __Uv1_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"

#include "Api.objc.h"

@interface Uv1 : NSObject
// skipped variable ChiaFullNodeClient with unsupported type: *vbh/taf-wallet/internal/chia/chia.Client

@end

FOUNDATION_EXPORT ApiAddCoinTypeResponse* _Nullable Uv1AddCoinType(ApiAddCoinTypeRequest* _Nullable req, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT ApiBackupMnemonicResponse* _Nullable Uv1BackupMnemonic(ApiBackupMnemonicRequest* _Nullable req, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT ApiCreateMnemonicResponse* _Nullable Uv1CreateMnemonic(ApiCreateMnemonicRequest* _Nullable req, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT ApiCreateWalletResponse* _Nullable Uv1CreateWallet(ApiCreateWalletRequest* _Nullable req, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT ApiEstimateEthGasResponse* _Nullable Uv1EstimateEthGas(ApiEstimateEthGasRequest* _Nullable req, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT ApiEstimateEthGasPriceResponse* _Nullable Uv1EstimateEthGasPrice(ApiEstimateEthGasPriceRequest* _Nullable req, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT ApiEstimateTransactionSizeResponse* _Nullable Uv1EstimateTransactionSize(ApiEstimateTransactionSizeRequest* _Nullable req, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT ApiExportPrivateKeyResponse* _Nullable Uv1ExportPrivateKey(ApiExportPrivateKeyRequest* _Nullable req, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT ApiExportPrivateKeyFromMasterResponse* _Nullable Uv1ExportPrivateKeyFromMaster(ApiExportPrivateKeyFromMasterRequest* _Nullable req, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT ApiFindMnemonicResponse* _Nullable Uv1FindMnemonic(ApiFindMnemonicRequest* _Nullable req, NSError* _Nullable* _Nullable error);

/**
 * 系统垃圾回收 注意：不是强制回收,会耗费系统资源
 */
FOUNDATION_EXPORT void Uv1GarbageCollection(void);

FOUNDATION_EXPORT ApiGetAddressBalanceResponse* _Nullable Uv1GetAddressBalance(ApiGetAddressBalanceRequest* _Nullable req, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT ApiGetAddressesTxIdsResponse* _Nullable Uv1GetAddressesTxIds(ApiGetAddressesTxIdsRequest* _Nullable req, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT ApiGetBlockHeaderResponse* _Nullable Uv1GetBlockHeader(ApiGetBlockHeaderRequest* _Nullable req, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT ApiGetBtcTransactionResponse* _Nullable Uv1GetBtcTransaction(ApiGetBtcTransactionRequest* _Nullable req, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT ApiQueryETHTransactionResponse* _Nullable Uv1GetETHTransactionReceipt(ApiQueryETHTransactionRequest* _Nullable req, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT ApiQueryTrxTransactionResponse* _Nullable Uv1GetTrxTransaction(ApiQueryTrxTransactionRequest* _Nullable req, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT ApiImportPrivateKeyResponse* _Nullable Uv1ImportPrivateKey(ApiImportPrivateKeyRequest* _Nullable req, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT ApiImportWalletFromMnemonicResponse* _Nullable Uv1ImportWalletFromMnemonic(ApiImportWalletFromMnemonicRequest* _Nullable req, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT ApiModifyPasswordResponse* _Nullable Uv1ModifyPassword(ApiModifyPasswordRequest* _Nullable req, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT ApiParamResponse* _Nullable Uv1ParamConfig(ApiParamRequest* _Nullable req, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT ApiQueryBtcTransactionResponse* _Nullable Uv1QueryTransaction(ApiQueryBtcTransactionRequest* _Nullable req, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT ApiRemoveKeyResponse* _Nullable Uv1RemoveKey(ApiRemoveKeyRequest* _Nullable req, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT ApiRemoveWalletResponse* _Nullable Uv1RemoveWallet(ApiRemoveWalletRequest* _Nullable req, NSError* _Nullable* _Nullable error);

/**
 * 发送交易
 */
FOUNDATION_EXPORT ApiETHTransactionResponse* _Nullable Uv1SendETHTransaction(ApiETHTransactionRequest* _Nullable req, BOOL fromKeystore, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT ApiAecoSignResponse* _Nullable Uv1Sign(ApiAecoSignRequest* _Nullable req, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT ApiAecoSignResponseFromMaster* _Nullable Uv1SignFromMaster(ApiAecoSignRequestFromMaster* _Nullable req, NSError* _Nullable* _Nullable error);

/**
 * 小写地址转换成EIP55的地址
 */
FOUNDATION_EXPORT ApiETHEipAddressResponse* _Nullable Uv1ToEip55Address(ApiETHEipAddressRequest* _Nullable req, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT ApiToTrxAddressResponse* _Nullable Uv1ToTrxAddress(ApiToTrxAddressRequest* _Nullable req, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT ApiTransactionFeeRateResponse* _Nullable Uv1TransactionFeeRate(ApiTransactionFeeRateRequest* _Nullable req, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT ApiTransferFromHdWalletResponse* _Nullable Uv1TransferFromHdWallet(ApiTransferFromHdWalletRequest* _Nullable req, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT ApiTransferResponse* _Nullable Uv1TransferFromKey(ApiTransferRequest* _Nullable req, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT ApiValidateAddressResponse* _Nullable Uv1ValidateAddress(ApiValidateAddressRequest* _Nullable req, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT ApiVerifyMnemonicResponse* _Nullable Uv1VerifyMnemonic(ApiVerifyMnemonicRequest* _Nullable req, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT ApiVerifyMultiMnemonicResponse* _Nullable Uv1VerifyMultiMnemonic(ApiVerifyMultiMnemonicRequest* _Nullable req, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT ApiVerifyWalletPasswordResponse* _Nullable Uv1VerifyWalletPassword(ApiVerifyWalletPasswordRequest* _Nullable req);

#endif
