
// Objective-C API for talking to the following Go packages
//
//	vbh/taf-wallet/api
//	vbh/taf-wallet/sdk
//	vbh/taf-wallet/sdk/v1
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Walletsdk_FRAMEWORK_H__
#define __Walletsdk_FRAMEWORK_H__

#include "Api.objc.h"
#include "Sdk.objc.h"
#include "Uv1.objc.h"
#include "Universe.objc.h"

#endif
